// Code generated by tailscale.com/cmd/cloner; DO NOT EDIT.

package quiz

import (
	"maps"
	"time"
)

// Clone makes a deep copy of Quiz.
// The result aliases no memory with the original.
func (src *Quiz) Clone() *Quiz {
	if src == nil {
		return nil
	}
	dst := new(Quiz)
	*dst = *src
	dst.Config = *src.Config.Clone()
	if src.Teams != nil {
		dst.Teams = make([]Team, len(src.Teams))
		for i := range dst.Teams {
			dst.Teams[i] = *src.Teams[i].Clone()
		}
	}
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _QuizCloneNeedsRegeneration = Quiz(struct {
	Version int
	Created time.Time
	Config  Config
	Teams   []Team
}{})

// Clone makes a deep copy of Config.
// The result aliases no memory with the original.
func (src *Config) Clone() *Config {
	if src == nil {
		return nil
	}
	dst := new(Config)
	*dst = *src
	dst.RoundMaxPoints = maps.Clone(src.RoundMaxPoints)
	dst.Checkpoints = append(src.Checkpoints[:0:0], src.Checkpoints...)
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _ConfigCloneNeedsRegeneration = Config(struct {
	Rounds            int
	QuestionsPerRound int
	RoundMaxPoints    map[string]int
	MaxPoints         int
	Checkpoints       []int
}{})

// Clone makes a deep copy of Team.
// The result aliases no memory with the original.
func (src *Team) Clone() *Team {
	if src == nil {
		return nil
	}
	dst := new(Team)
	*dst = *src
	dst.Scores = maps.Clone(src.Scores)
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _TeamCloneNeedsRegeneration = Team(struct {
	ID      string
	Name    string
	Players string
	Scores  map[string]float64
}{})
